apiVersion: hydros.dev/v1alpha1
kind: RepoConfig
metadata:
  name: repo
  namespace: somenamespace
spec:
  repo: https://github.com/yourproject/code.git
  gitHubAppConfig:
    appID: 384797
    privateKey: gcpsecretmanager:///projects/yourproject/secrets/hydros-ghapp-key/versions/latest
  globs:
    - "**/*.yaml"
  selectors:
    - matchLabels:
        env: dev
