kind: Image
apiVersion: hydros.sailplane.ai/v1alpha1
metadata:
  name: hydros
  namespace: hydros
spec:
  source:
    - src: Dockerfile
    # Specify individual directories so we don't include hidden directories
    - src: "api/**/*.go"
    - src: "cmd/**/*.go"
    - src: "pkg/**/*.go"
    - src: "test/**/*.go"
  builder:
    gcb:
      buildFile: cloudbuild.yaml
