kind: Image
apiVersion: hydros.dev/v1alpha1
metadata:
  name: hydros
  namespace: hydros
  labels:
    env: release
spec:
  image: us-west1-docker.pkg.dev/foyle-public/images/hydros/hydros
  source:
    - uri: https://github.com/jlewi/hydros.git
      mappings:
      - src: Dockerfile
      # Specify individual directories so we don't include hidden directories
      - src: "go.mod"
      - src: "go.sum"
      - src: "api/**/*.go"
      - src: "cmd/**/*.go"
      - src: "pkg/**/*.go"
      - src: "test/**/*.go"
    # Pull in kustomize from its docker image
    - uri: docker://registry.k8s.io/kustomize/kustomize:v5.0.0
      mappings:
        - src: app/kustomize
          strip: app
  builder:
    gcb:
      project: foyle-public
      bucket : builds-foyle-public
