apiVersion: apps/v1
kind: Deployment
metadata:
  name: hydros
spec:
  template:
    spec:
      containers:
        - name: hydros
          env:
            - name: OPENAI_API_KEY
              value: gcpSecretManager:///projects/chat-lewi/secrets/openai-api-key/versions/latest