# Add an HTTPRoute to connect the loadbalancer to the istio-ingressgateway
kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: hydros-webhook
spec:
  parentRefs:
    - kind: Gateway
      name: platform
      namespace: gateway
  hostnames:
    - "platform.roboweb.app"
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: "/hydros/"
      backendRefs:
        - name: hydros
          port: 8080
