apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  labels:
    app: hydros
    environment: lewi
resources:
- ../base
- namespace.yaml
images:
- name: hydros
  newName: us-west1-docker.pkg.dev/chat-lewi/hydros/hydros
  newTag: a3844ec8-bded-4487-bb28-47268cdbc836
