apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  labels:
    app: hydros
    environment: lewi
resources:
- ../base
- backendconfig.yaml
- namespace.yaml
- httproute.yaml
patches:
- path: service.patch.yaml
- path: serviceaccount.patch.yaml
images:
- name: hydros
  newName: us-west1-docker.pkg.dev/chat-lewi/hydros/hydros
  newTag: 7b3f4e24-51ba-4e16-a79d-8be2425dea7f
